### ISSUE TITLE
[Epic] Revamp Planner DevOps

### ISSUE THREAD

**Issue by debloper** [fabric8-ui/fabric8-planner#2383]
Looking ahead towards Planner as a standalone app, we need to rework the overall orchestration.

- [ ] Review and consolidate directory structure #2382
- [ ] Refactor NPM scripts #2376
- [ ] Revamp build system with RollupJS #1920 
- [ ] Redesign automation pipeline with clearer abstraction, documentation and separation of concerns #2381
